//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBSync.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string EQUAL {
            get {
                return ResourceManager.GetString("EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal.
        /// </summary>
        internal static string NOT_EQ {
            get {
                return ResourceManager.GetString("NOT_EQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string REMOVED {
            get {
                return ResourceManager.GetString("REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEMA.
        /// </summary>
        internal static string SCHEMA {
            get {
                return ResourceManager.GetString("SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRIPT COMPLETED.
        /// </summary>
        internal static string SCRIPT_COMPLETED {
            get {
                return ResourceManager.GetString("SCRIPT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure.
        /// </summary>
        internal static string SP {
            get {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML SCHEMA.
        /// </summary>
        internal static string XML_SCHEMA {
            get {
                return ResourceManager.GetString("XML_SCHEMA", resourceCulture);
            }
        }
    }
}
